name: Build Vantage

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}
    
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build App
        run: npm run build

      - name: Package for Windows
        if: matrix.os == 'windows-latest'
        run: npx electron-builder --win portable

      - name: Package for Linux
        if: matrix.os == 'ubuntu-latest'
        run: npx electron-builder --linux

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Vantage-${{ matrix.os }}
          path: |
            dist/*.exe
            dist/*.AppImage
            dist/*.deb

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest Distribution
          files: |
            dist/*.exe
            dist/*.AppImage
            dist/*.deb
          generate_release_notes: true
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}